services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_SITE_URL: ${MB_SITE_URL}
      MB_ENCRYPTION_SECRET_KEY: ${MB_ENCRYPTION_SECRET_KEY}
      MB_PASSWORD_COMPLEXITY: normal
      MB_PASSWORD_LENGTH: 8
    restart: unless-stopped
