version: 2

sources:
  - name: raw_ons
    schema: RAW_ONS
    tables:
      - name: BALANCO_ENERGIA_SUBSISTEMA_2025
      - name: BALANCO_ENERGIA_SUBSISTEMA_2024
      - name: BALANCO_ENERGIA_SUBSISTEMA_2023
      - name: DISPONIBILIDADE_USINA_GERAL
      - name: EAR_DIARIO_SUBSISTEMA_2025
      - name: EAR_DIARIO_SUBSISTEMA_2024
      - name: EAR_DIARIO_SUBSISTEMA_2023
      - name: ENA_DIARIO_SUBSISTEMA_2025
      - name: INMET_PROCESSED_DATA

      # Tabelas de 2024
      - name: GERACAO_TERMICA_DESPACHO_2024_01
      - name: GERACAO_TERMICA_DESPACHO_2024_02
      - name: GERACAO_TERMICA_DESPACHO_2024_03
      - name: GERACAO_TERMICA_DESPACHO_2024_04
      - name: GERACAO_TERMICA_DESPACHO_2024_05
      - name: GERACAO_TERMICA_DESPACHO_2024_06
      - name: GERACAO_TERMICA_DESPACHO_2024_07
      - name: GERACAO_TERMICA_DESPACHO_2024_08
      - name: GERACAO_TERMICA_DESPACHO_2024_09
      - name: GERACAO_TERMICA_DESPACHO_2024_10
      - name: GERACAO_TERMICA_DESPACHO_2024_11
      - name: GERACAO_TERMICA_DESPACHO_2024_12
      
      # Tabelas de 2025
      - name: GERACAO_TERMICA_DESPACHO_2025_01
      - name: GERACAO_TERMICA_DESPACHO_2025_02
      - name: GERACAO_TERMICA_DESPACHO_2025_03
      - name: GERACAO_TERMICA_DESPACHO_2025_04
      - name: GERACAO_TERMICA_DESPACHO_2025_05
      - name: GERACAO_TERMICA_DESPACHO_2025_06
      - name: GERACAO_TERMICA_DESPACHO_2025_07
      - name: GERACAO_TERMICA_DESPACHO_2025_08
      - name: GERACAO_TERMICA_DESPACHO_2025_09